version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network: